--DATA CLEANING
--Q1.What is the total number of rows ?
select count(*) from Transactions$

--Q2.What is the total number of transactions that have a return ?
select count(transaction_id)  from Transactions$ where Qty<0;

--Q3.As you would have noticed, the dates provided across the datasets are not in a correct format. 
---As first steps, pls convert the date variables into valid date formats before proceeding ahead.
UPDATE Transactions$
SET tran_date = CONVERT(DATE, tran_date,105)
ALTER TABLE Transactions$
ALTER COLUMN tran_date DATE;

--Q4.What is the time range of the transaction data available for analysis? Show the output in number of days, 
----months and years simultaneously in different columns.
select DATEDIFF(year,min(tran_date),max(tran_date))  year ,
 DATEDIFF(month,min(tran_date),max(tran_date))  months ,
 DATEDIFF(DAY,min(tran_date),max(tran_date))  days from Transactions$ ;

 --Q5.Which product category does the sub-category “DIY” belong to?
 select prod_cat from prod_cat_info$ where prod_subcat='DIY';

---DATA ANALYSIS
 --Q1 Which channel is most frequently used for transactions?
 select top 1  store_type, count(store_type) cnt from Transactions$ group by
 Store_type order by cnt desc;

 --Q2.What is the count of Male and Female customers in the database?
 select Gender ,count(Gender) from Customer$ 
 where gender is not null group by Gender ;

 --Q3.From which city do we have the maximum number of customers and how many?
 select top 1  count(customer_id)  cnt , city_code from Customer$
 group by city_code order by cnt desc;

 --Q4.How many sub-categories are there under the Books category?
 select prod_cat , count(prod_subcat) sub_cat_number
 from prod_cat_info$ 
 where prod_cat='Books'
 group by prod_cat  ;

 --Q5.What is the maximum quantity of products ever ordered?
 select top 1  prod_cat, sum (Qty) cnt  from
 Transactions$ a join prod_cat_info$ b on a.prod_subcat_code=b.prod_sub_cat_code 
 and a.prod_cat_code=b.prod_cat_code where qty>1
 group by prod_cat  order by cnt desc ;

 --Q6.What is the net total revenue generated in categories Electronics and Books?
 select   sum(total_amt)  Revenue  from  Transactions$ a 
 join prod_cat_info$ b
 on a.prod_subcat_code=b.prod_sub_cat_code
 and a.prod_cat_code=b.prod_cat_code where
 prod_cat in ('Electronics','Books');

 --Q7.How many customers have >10 transactions with us, excluding returns?
 select count(*)  Total_customers
 from (
 select cust_id   from
 Transactions$ where Qty>0  group by cust_id 
 having count(transaction_id)>10 ) l ;

 --Q8.What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
 SELECT sum(total_amt)  revenue  from Transactions$ a join prod_cat_info$ b on
 a.prod_subcat_code=b.prod_sub_cat_code  
 and a.prod_cat_code=b.prod_cat_code where prod_cat in 
 ('Electronics' ,'Clothing') 
 and store_type='Flagship store' ;

 --Q9.What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.
select round(sum(total_amt),3)  Revenue_by_male , prod_subcat  from Transactions$   a join prod_cat_info$ b
 on a.prod_subcat_code=b.prod_sub_cat_code join Customer$  c on  a.cust_id=c.customer_Id
 and a.prod_cat_code=b.prod_cat_code where  Gender ='M' and prod_cat='Electronics' group by prod_subcat;

--Q10.What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
select prod_subcat , sum( case when Qty>0 then Qty else 0 end )*100 / (  select sum(QTY)  from Transactions$ where Qty>0    ) percentage_sales ,
sum( case when Qty<0 then Qty else 0 end ) *100/ (  select sum( Qty )   from Transactions$ where Qty<0 ) return_percentage
from Transactions$  q  join prod_cat_info$ w on
q.prod_subcat_code=w.prod_sub_cat_code
and q.prod_cat_code=w.prod_cat_code
where prod_subcat in 
(
select top 5 prod_subcat from Transactions$ f
join prod_cat_info$ g on
f.prod_subcat_code=g.prod_sub_cat_code
and f.prod_cat_code=g.prod_cat_code
where Qty>1
group by prod_subcat order by sum(Qty) desc )
group by prod_subcat order by percentage_sales desc ;

--Q11.For all customers aged between 25 to 35 years find what is the net total revenue 
 --generated by these consumers in last 30 days of transactions from max transaction date available in the data?
select sum(revenue) net_revenue from
(
select  datediff(year, DOB ,max(tran_date)) age , cust_id,
sum(total_amt)  revenue 
from Transactions$ v join Customer$ s  on v.cust_id=s.customer_Id
where tran_date>=DATEADD(day,-30,(select max(tran_date) FROM Transactions$))
group by cust_id ,DOB having datediff(year, DOB ,max(tran_date)) between 25 and 35) n ;


--Q12.Which product category has seen the max value of returns in the last 3 month of transactions ?
select  top 1 abs(sum(total_amt)),  prod_cat from Transactions$ a join Customer$ b 
on a.cust_id=b.customer_Id join prod_cat_info$ c
on a.prod_cat_code=c.prod_cat_code  where Qty<0 and 
tran_date>=DATEADD(month,-3,(select(max(tran_date)) from Transactions$))
group by prod_cat order by abs (sum(total_amt) )desc;


--Q13.Which store_type sells the most quantity and has max_amount  of sales  ?
select  top 1 store_type ,round(sum(total_amt),2) SUM ,  sum(Qty) QUANTITY
from Transactions$  where qty>1 group by 
Store_type order by  SUM desc , QUANTITY desc;

--Q14.Categories for which average revenue is above the overall total average revenue ?
select prod_cat from Transactions$  x join  prod_cat_info$ y on 
x.prod_subcat_code=y.prod_sub_cat_code  and x.prod_cat_code=y.prod_cat_code where Qty>0
group by prod_cat  having AVG(total_amt) > (select avg(total_amt) from Transactions$) ;

--Q15.Find the average and total revenue by each sub-category for the categories that are among top 5 categories in terms of quantity sold.
select prod_subcat, avg(total_amt) average_revenue  ,sum(total_amt) total_revenue from   Transactions$ a 
join prod_cat_info$ b on
a.prod_subcat_code=b.prod_sub_cat_code   and b.prod_cat_code=a.prod_cat_code where prod_cat
in (
select  top  5 prod_cat from Transactions$ a join prod_cat_info$ b on
a.prod_subcat_code=b.prod_sub_cat_code   and b.prod_cat_code=a.prod_cat_code 
group by prod_cat order by sum(qty) desc) group by  prod_subcat;































